# Generated by Django 4.0.2 on 2022-02-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0002_alter_book_sell_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rent_profit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
