# Generated by Django 4.0.2 on 2022-02-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0003_book_rent_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rent_price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
